#+title: そうは言ってもちょっと気になる人のための、ゆるやかなEmacs再入門
#+author: conao3
#+date: <2019-06-17 Mon>

* Emacsとは
初心者研修もとっくに終わり、どんどん業務に取りかかろうとしている季節だと思います。
EmacsやVimの説明を受ける機会や上司からそれらを押しつけられた機会があり、Twitterに恨み節を書き込んだ経験もあろうかと思います。

しかし、あなたの中には「Emacsは挫折したけど、使いこなせるとすごいんだろうな」「実際、EmacsとVimは素養として身に付けておきたいな」
といった気持ちがあるのではないでしょうか。

そして、Emacsをもし使えるようになれば、その副作用として、何の苦もなく「エンジニア」との話題を一つ確保できることになります。
「Emacsなんか古めかしい。時代はVSCodeだ。」や、「おっ。Emacs使ってるの。昔はEmacsのMewでメールを打ってたものだ」など
どの方向に行くかはさておき、雑談の話題を一つ得ることができます。

さらに言えば「Emacsを使っている」という共通点だけでEmacs-JPのようなさまざまな業種のエンジニアが集まるユーザーコミュニティに
参加することができたり、Emacsの拡張をしようと思うなら「関数型言語」であるLispの知識も得ることができ、
Emacsの魅力もさることながら、その副作用もとても大きなものだと思っています。

ぜひこの記事があなたのEmacsへの恐怖心を少しでも取り除き、Emacsに再入門するきっかけとなれば幸いです。

(なお、私は高校1年生のときに、大学に訪問する機会があり、そこでお会いしたコンパイラを専門にしている教授から実際の「Emacs」を見せて頂きました。
「Emacs」というエディタは名だたるスーパーハッカーに愛されていたことは知っていましたが、使ってみたことはありませんでした。

高校では年1回、入門してそれぞれで3回挫折しました。
私が本格的にEmacsを使うようになったのは、大学に入ってからです。

今ではEmacsは私にとってなくてはならない存在となり、各国のエンジニアと一緒にEmacsのパッケージを作ったりメンテナンスをしたり、
Emacs-JPの勉強会で登壇したりと、とても楽しい経験を間接的にも直接的にももたらしてくれたツールになりました。

Emacsはあなたにも少なからざるものを与えてくれると信じています。)

そして私はVim/Emacs論争に加担することはありません。
私も両方使えますし、上に書いたとおり、VimとEmacsが使えることはエンジニアの素養だと思います。

しかし私は基本操作だけしか使えないので、私はEmacsの記事を書きます。

* カーソル移動について

