#+title: Installation
#+date: <2018-07-15 Sun>

* Installation
Org is part of recent distributions of GNU Emacs, so you normally don’t need to install it. If, for one reason or another, you want to install Org on top of this pre-packaged version, there are three ways to do it:

- By using Emacs package system.
- By downloading Org as an archive.
- By using Org’s git repository.


We *strongly recommend* to stick to a single installation method.

*** Using Emacs packaging system
 Recent Emacs distributions include a packaging system which lets you install Elisp libraries. You can install Org with M-x package-install RET org.

 *Important* : you need to do this in a session where no .org file has been visited, i.e., where no Org built-in function have been loaded. Otherwise autoload Org functions will mess up the installation.

 Then, to make sure your Org configuration is taken into account, initialize the package system with (package-initialize) in your Emacs init file before setting any Org option. If you want to use Org’s package repository, check out the Org ELPA page.

**** Downloading Org as an archive
  You can download Org latest release from Org’s website. In this case, make sure you set the load-path correctly in your Emacs init file:

  (add-to-list 'load-path "~/path/to/orgdir/lisp")
  The downloaded archive contains contributed libraries that are not included in Emacs. If you want to use them, add the contrib directory to your load-path:

  (add-to-list 'load-path "~/path/to/orgdir/contrib/lisp" t)
  Optionally, you can compile the files and/or install them in your system. Run make help to list compilation and installation options.

***** Using Org’s git repository
   You can clone Org’s repository and install Org like this:
   #+BEGIN_SRC bash
   $ cd ~/src/
   $ git clone https://code.orgmode.org/bzg/org-mode.git
   $ cd org-mode/
   $ make autoloads
   #+END_SRC
   Note that in this case, make autoloads is mandatory: it defines Org’s version in org-version.el and Org’s autoloads in org-loaddefs.el.

   Remember to add the correct load-path as described in the method above.

   You can also compile with make, generate the documentation with make doc, create a local configuration with make config and install Org with make install. Please run make help to get the list of compilation/installation options.

   For more detailed explanations on Org’s build system, please check the Org Build System page on Worg.
   #+BEGIN_SRC elisp
   (defvar orglyth-root-path "~/public_html/orglyth/"
     "orglyth sorce root path.")

   (defvar orglyth-sorce-path (concat orglyth-root-path "src/")
     "orglyth sorce path.")

   (defvar orglyth-build-path (concat orglyth-root-path "build/")
     "orglyth dest path.")

   (defvar orglyth-template-parts-path (concat orglyth-root-path "parts/")
     "orglyth template parts path.")
   #+END_SRC

   | sf | asdf |
   |    | asdf |

   $\sum_{i=1}^n a_i x_i \ge b$ の時
   [[file:page01.org][ヘッダ]]

   #+BEGIN_SRC html
   <ul class="org-ul">
   <li>By using Emacs package system.</li>
   <li>By downloading Org as an archive.</li>
   <li>By using Org’s git repository.</li>
   </ul>
   #+END_SRC
